name: ${name}
version: ${version}
main: me.suzutsuki.Bukkit.Quizzer.Quizzer
permissions:
    quizzer.admin:
        default: op
commands:
    quiz:
        permission: quizzer.admin
        usage: /quiz